project_name: mindthegap
gomod:
  proxy: true
  env:
    - GOPRIVATE=github.com/mesosphere
builds:
  - id: mindthegap
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X 'k8s.io/component-base/version.buildDate={{ .CommitDate }}'
      - -X 'k8s.io/component-base/version.gitCommit={{ .FullCommit }}'
      - -X 'k8s.io/component-base/version.gitTreeState={{ .Env.GIT_TREE_STATE }}'
      - -X 'k8s.io/component-base/version.gitVersion=v{{ trimprefix .Version "v" }}'
      - -X 'k8s.io/component-base/version.gitMajor={{ .Major }}'
      - -X 'k8s.io/component-base/version.gitMinor={{ .Minor }}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    hooks:
      pre: |
        make GOOS={{ .Os }} GOARCH={{ .Arch }} skopeo.build
        make SKIP_UPX={{ .IsSnapshot }} GOOS={{ .Os }} GOARCH={{ .Arch }} UPX_TARGET=skopeo/static/skopeo-{{ .Os }}-{{ .Arch }} upx
      post: |
        make SKIP_UPX={{ .IsSnapshot }} GOOS={{ .Os }} GOARCH={{ .Arch }} UPX_TARGET={{ .Path }} upx
universal_binaries:
  - replace: true
    id: mindthegap
archives:
  - name_template: '{{ .ProjectName }}_v{{trimprefix .Version "v"}}_{{ .Os }}_{{ .Arch }}'
  # This is a hack documented in https://github.com/goreleaser/goreleaser/blob/df0216d5855e9283d2106fb5acdb0e7b528a56e8/www/docs/customization/archive.md#packaging-only-the-binaries
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incminor .Tag }}-dev"
changelog:
  filters:
    exclude:
      - '^(refactor|chore|docs|build):'
